version: '2'
services:
  hana:
    image: store/saplabs/hanaexpress:2.00.040.00.20190729.1
    privileged: True
    ports:
     - 39013:39013
     - 39017:39017
     - 39041-39045:39041-39045
     - 1128-1129:1128-1129
     - 59013-59014:59013-59014
    command:
     - --agree-to-sap-license
     - --dont-check-system
     - --dont-check-mount-points
     - --master-password
     - Sap-hana-s3cret
